import { CopyOutlined, SafetyCertificateOutlined } from '@ant-design/icons';
import { Button, Form, Input, Modal, Skeleton, Space, Typography, message } from 'antd';
import { QRCodeSVG } from 'qrcode.react';
import { useMutation, useQuery } from '@tanstack/react-query';
import { authApi } from '../../api/auth.api';
import { DisableTwoFactorSchema, TwoFactorCodeSchema, type DisableTwoFactorInput, type TwoFactorCodeInput } from '../../schemas/auth.schema';
import { validateWithZod } from '../../utils/zodForm';

export default function TwoFactorForm() {
  const [confirmForm] = Form.useForm<TwoFactorCodeInput>();
  const [disableForm] = Form.useForm<DisableTwoFactorInput>();
  const setupQuery = useQuery({
    queryKey: ['auth', '2fa', 'setup'],
    queryFn: authApi.setupTwoFactor,
  });

  const confirmMutation = useMutation({
    mutationFn: authApi.confirmTwoFactorSetup,
    onSuccess: () => message.success('2FA đã được bật'),
    onError: (err: Error) => message.error(err.message || 'Không thể xác nhận 2FA'),
  });

  const disableMutation = useMutation({
    mutationFn: authApi.disableTwoFactor,
    onSuccess: () => message.success('2FA đã được tắt'),
    onError: (err: Error) => message.error(err.message || 'Không thể tắt 2FA'),
  });

  const onDisable = () => {
    Modal.confirm({
      title: 'Tắt xác thực 2 yếu tố',
      content: (
        <Form<DisableTwoFactorInput> form={disableForm} layout="vertical" className="mt-4">
          <Form.Item name="totpCode" label="TOTP Code">
            <Input inputMode="numeric" maxLength={6} placeholder="123456" />
          </Form.Item>
          <Form.Item name="password" label="Current Password">
            <Input.Password placeholder="••••••••" />
          </Form.Item>
        </Form>
      ),
      okText: 'Disable 2FA',
      okButtonProps: { danger: true },
      onOk: async () => {
        const values = await disableForm.validateFields();
        const parsed = validateWithZod(DisableTwoFactorSchema, values, disableForm);
        if (!parsed) return Promise.reject();
        disableMutation.mutate(parsed);
      },
    });
  };

  return (
    <div className="grid gap-6 lg:grid-cols-[1.2fr_0.8fr]">
      <section className="rounded-xl border border-outline-variant bg-white p-6">
        <div className="mb-6 flex items-start justify-between gap-4">
          <div>
            <h2 className="font-headline text-2xl font-bold text-on-surface">Enable Two-Factor Authentication</h2>
            <p className="mt-2 text-sm leading-6 text-on-surface-variant">
              Scan the QR code with Google Authenticator, 1Password, or another TOTP app.
            </p>
          </div>
          <span className="rounded-full border border-outline-variant bg-surface-container-high px-3 py-1 text-xs font-semibold text-on-surface-variant">
            Pending Verification
          </span>
        </div>
        {setupQuery.isLoading ? (
          <Skeleton active paragraph={{ rows: 6 }} />
        ) : (
          <div className="grid gap-6 md:grid-cols-[220px_1fr]">
            <div className="flex h-56 items-center justify-center rounded-lg border border-outline-variant bg-surface">
              {setupQuery.data?.uri ? <QRCodeSVG value={setupQuery.data.uri} size={176} /> : <SafetyCertificateOutlined className="text-5xl text-outline" />}
            </div>
            <div>
              <Typography.Text strong>Manual Secret Key</Typography.Text>
              <div className="mt-3 flex items-center gap-2 rounded-lg border border-outline-variant bg-surface-container-high p-3">
                <code className="flex-1 break-all font-mono text-sm">{setupQuery.data?.secret ?? 'Waiting for server secret'}</code>
                <Button
                  aria-label="Copy secret"
                  icon={<CopyOutlined />}
                  onClick={() => {
                    if (setupQuery.data?.secret) navigator.clipboard.writeText(setupQuery.data.secret);
                  }}
                />
              </div>
              {setupQuery.isError ? <p className="mt-3 text-sm text-error">{(setupQuery.error as Error).message}</p> : null}
            </div>
          </div>
        )}
      </section>
      <section className="rounded-xl border border-outline-variant bg-white p-6">
        <h3 className="font-headline text-xl font-bold">Verification</h3>
        <p className="mt-2 text-sm leading-6 text-on-surface-variant">Enter the 6-digit code generated by your authenticator app.</p>
        <Form<TwoFactorCodeInput>
          form={confirmForm}
          layout="vertical"
          className="mt-6"
          onFinish={(values) => {
            const parsed = validateWithZod(TwoFactorCodeSchema, values, confirmForm);
            if (parsed) confirmMutation.mutate(parsed);
          }}
        >
          <Form.Item name="totpCode" label="TOTP Code">
            <Input size="large" inputMode="numeric" maxLength={6} placeholder="123456" />
          </Form.Item>
          <Space direction="vertical" className="w-full">
            <Button block type="primary" htmlType="submit" loading={confirmMutation.isPending}>
              Enable 2FA
            </Button>
            <Button block danger onClick={onDisable} loading={disableMutation.isPending}>
              Disable 2FA
            </Button>
          </Space>
        </Form>
      </section>
    </div>
  );
}
